# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 16:02:57 2020/07/14 二
#     > Comment     :
# *****************************************************

make :
	g++ ./client.c 

run :
	./a.out 123.57.102.65 8888

open :
	vim ./client.c

