# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 15:07:26 2020/07/17 五
#     > Comment     :
# *****************************************************

make :
	g++ ./test.c

run :
	./a.out 123.57.102.65 9008

