# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 17:00:20 2020/07/16 四
#     > Comment     :
# *****************************************************
make :
	g++ ./test.c

run :
	./a.out 123.57.102.65 9007 
