# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 15:32:21 2020/07/15 三
#     > Comment     :
# *****************************************************

make : ./server.c ./common.c
	g++ server.c common.c -o server

	

