# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 15:13:57 2020/07/16 四
#     > Comment     :
# *****************************************************

make : ./process_multi.c
	g++ ./process_multi.c

open :
	vim ./process_multi.c
