# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 16:57:52 2020/07/16 四
#     > Comment     :
# *****************************************************

make : ./server.c ./common.c
	g++ ./server.c ./common.c -lpthread

open :
	vim ./server.c
