# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 16:23:23 2020/07/16 四
#     > Comment     :
# *****************************************************

make : ./add_thread_multi.c
	g++ ./add_thread_multi.c -lpthread

open :
	vim ./add_thread_multi.c

run :
	./a.out
