# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 15:32:21 2020/07/15 三
#     > Comment     :
# *****************************************************

make : 
	g++ client.c ../server/common.c -o client

open :
	vim ./client.c

run :
	./client 127.0.0.1 8888 
